// GENERATED by scripts/gen-adjustments.py from the installed Capture One sdef.
// Do not hand-edit; re-run the generator instead.

export interface AdjustmentProperty {
  /** Tool-facing snake_case parameter name. */
  param: string;
  /** JXA property name on `variant.adjustments`. */
  jxa: string;
  /** Name as it appears in the scripting dictionary. */
  dictionary: string;
  kind: "real" | "integer" | "boolean" | "enum" | "text";
  /** Allowed values, for enum-typed properties. */
  values?: readonly string[];
}

export const ADJUSTMENT_PROPERTIES: readonly AdjustmentProperty[] = [
  { param: "orientation", jxa: "orientation", dictionary: "orientation", kind: "integer" },
  { param: "rotation", jxa: "rotation", dictionary: "rotation", kind: "real" },
  { param: "flip", jxa: "flip", dictionary: "flip", kind: "enum", values: ["none", "horizontal", "vertical"] as const },
  { param: "keystone_amount", jxa: "keystoneAmount", dictionary: "keystone amount", kind: "integer" },
  { param: "keystone_vertical", jxa: "keystoneVertical", dictionary: "keystone vertical", kind: "real" },
  { param: "keystone_horizontal", jxa: "keystoneHorizontal", dictionary: "keystone horizontal", kind: "real" },
  { param: "keystone_skew", jxa: "keystoneSkew", dictionary: "keystone skew", kind: "real" },
  { param: "keystone_aspect", jxa: "keystoneAspect", dictionary: "keystone aspect", kind: "real" },
  { param: "color_profile", jxa: "colorProfile", dictionary: "color profile", kind: "text" },
  { param: "film_curve", jxa: "filmCurve", dictionary: "film curve", kind: "text" },
  { param: "white_balance_preset", jxa: "whiteBalancePreset", dictionary: "white balance preset", kind: "text" },
  { param: "temperature", jxa: "temperature", dictionary: "temperature", kind: "real" },
  { param: "tint", jxa: "tint", dictionary: "tint", kind: "real" },
  { param: "exposure", jxa: "exposure", dictionary: "exposure", kind: "real" },
  { param: "brightness", jxa: "brightness", dictionary: "brightness", kind: "real" },
  { param: "contrast", jxa: "contrast", dictionary: "contrast", kind: "real" },
  { param: "saturation", jxa: "saturation", dictionary: "saturation", kind: "real" },
  { param: "color_balance_master_hue", jxa: "colorBalanceMasterHue", dictionary: "color balance master hue", kind: "real" },
  { param: "color_balance_master_saturation", jxa: "colorBalanceMasterSaturation", dictionary: "color balance master saturation", kind: "real" },
  { param: "color_balance_shadow_hue", jxa: "colorBalanceShadowHue", dictionary: "color balance shadow hue", kind: "real" },
  { param: "color_balance_shadow_saturation", jxa: "colorBalanceShadowSaturation", dictionary: "color balance shadow saturation", kind: "real" },
  { param: "color_balance_shadow_lightness", jxa: "colorBalanceShadowLightness", dictionary: "color balance shadow lightness", kind: "real" },
  { param: "color_balance_midtone_hue", jxa: "colorBalanceMidtoneHue", dictionary: "color balance midtone hue", kind: "real" },
  { param: "color_balance_midtone_saturation", jxa: "colorBalanceMidtoneSaturation", dictionary: "color balance midtone saturation", kind: "real" },
  { param: "color_balance_midtone_lightness", jxa: "colorBalanceMidtoneLightness", dictionary: "color balance midtone lightness", kind: "real" },
  { param: "color_balance_highlight_hue", jxa: "colorBalanceHighlightHue", dictionary: "color balance highlight hue", kind: "real" },
  { param: "color_balance_highlight_saturation", jxa: "colorBalanceHighlightSaturation", dictionary: "color balance highlight saturation", kind: "real" },
  { param: "color_balance_highlight_lightness", jxa: "colorBalanceHighlightLightness", dictionary: "color balance highlight lightness", kind: "real" },
  { param: "black_and_white", jxa: "blackAndWhite", dictionary: "black and white", kind: "boolean" },
  { param: "black_and_white_red_sensitivity", jxa: "blackAndWhiteRedSensitivity", dictionary: "black and white red sensitivity", kind: "integer" },
  { param: "black_and_white_yellow_sensitivity", jxa: "blackAndWhiteYellowSensitivity", dictionary: "black and white yellow sensitivity", kind: "integer" },
  { param: "black_and_white_green_sensitivity", jxa: "blackAndWhiteGreenSensitivity", dictionary: "black and white green sensitivity", kind: "integer" },
  { param: "black_and_white_cyan_sensitivity", jxa: "blackAndWhiteCyanSensitivity", dictionary: "black and white cyan sensitivity", kind: "integer" },
  { param: "black_and_white_blue_sensitivity", jxa: "blackAndWhiteBlueSensitivity", dictionary: "black and white blue sensitivity", kind: "integer" },
  { param: "black_and_white_magenta_sensitivity", jxa: "blackAndWhiteMagentaSensitivity", dictionary: "black and white magenta sensitivity", kind: "integer" },
  { param: "black_and_white_split_highlight_hue", jxa: "blackAndWhiteSplitHighlightHue", dictionary: "black and white split highlight hue", kind: "integer" },
  { param: "black_and_white_split_highlight_saturation", jxa: "blackAndWhiteSplitHighlightSaturation", dictionary: "black and white split highlight saturation", kind: "integer" },
  { param: "black_and_white_split_shadow_hue", jxa: "blackAndWhiteSplitShadowHue", dictionary: "black and white split shadow hue", kind: "integer" },
  { param: "black_and_white_split_shadow_saturation", jxa: "blackAndWhiteSplitShadowSaturation", dictionary: "black and white split shadow saturation", kind: "integer" },
  { param: "level_highlight_rgb", jxa: "levelHighlightRgb", dictionary: "level highlight rgb", kind: "real" },
  { param: "level_shadow_rgb", jxa: "levelShadowRgb", dictionary: "level shadow rgb", kind: "real" },
  { param: "level_highlight_red", jxa: "levelHighlightRed", dictionary: "level highlight red", kind: "real" },
  { param: "level_shadow_red", jxa: "levelShadowRed", dictionary: "level shadow red", kind: "real" },
  { param: "level_highlight_green", jxa: "levelHighlightGreen", dictionary: "level highlight green", kind: "real" },
  { param: "level_shadow_green", jxa: "levelShadowGreen", dictionary: "level shadow green", kind: "real" },
  { param: "level_highlight_blue", jxa: "levelHighlightBlue", dictionary: "level highlight blue", kind: "real" },
  { param: "level_shadow_blue", jxa: "levelShadowBlue", dictionary: "level shadow blue", kind: "real" },
  { param: "level_target_highlight_rgb", jxa: "levelTargetHighlightRgb", dictionary: "level target highlight rgb", kind: "real" },
  { param: "level_target_shadow_rgb", jxa: "levelTargetShadowRgb", dictionary: "level target shadow rgb", kind: "real" },
  { param: "level_target_highlight_red", jxa: "levelTargetHighlightRed", dictionary: "level target highlight red", kind: "real" },
  { param: "level_target_shadow_red", jxa: "levelTargetShadowRed", dictionary: "level target shadow red", kind: "real" },
  { param: "level_target_highlight_green", jxa: "levelTargetHighlightGreen", dictionary: "level target highlight green", kind: "real" },
  { param: "level_target_shadow_green", jxa: "levelTargetShadowGreen", dictionary: "level target shadow green", kind: "real" },
  { param: "level_target_highlight_blue", jxa: "levelTargetHighlightBlue", dictionary: "level target highlight blue", kind: "real" },
  { param: "level_target_shadow_blue", jxa: "levelTargetShadowBlue", dictionary: "level target shadow blue", kind: "real" },
  { param: "level_midtone_rgb", jxa: "levelMidtoneRgb", dictionary: "level midtone rgb", kind: "real" },
  { param: "level_midtone_red", jxa: "levelMidtoneRed", dictionary: "level midtone red", kind: "real" },
  { param: "level_midtone_green", jxa: "levelMidtoneGreen", dictionary: "level midtone green", kind: "real" },
  { param: "level_midtone_blue", jxa: "levelMidtoneBlue", dictionary: "level midtone blue", kind: "real" },
  { param: "highlight_recovery", jxa: "highlightRecovery", dictionary: "highlight recovery", kind: "real" },
  { param: "highlight_adjustment", jxa: "highlightAdjustment", dictionary: "highlight adjustment", kind: "real" },
  { param: "shadow_recovery", jxa: "shadowRecovery", dictionary: "shadow recovery", kind: "real" },
  { param: "white_recovery", jxa: "whiteRecovery", dictionary: "white recovery", kind: "real" },
  { param: "black_recovery", jxa: "blackRecovery", dictionary: "black recovery", kind: "real" },
  { param: "clarity_method", jxa: "clarityMethod", dictionary: "clarity method", kind: "enum", values: ["natural", "punch", "neutral", "classic"] as const },
  { param: "clarity_amount", jxa: "clarityAmount", dictionary: "clarity amount", kind: "real" },
  { param: "clarity_structure", jxa: "clarityStructure", dictionary: "clarity structure", kind: "real" },
  { param: "dehaze_amount", jxa: "dehazeAmount", dictionary: "dehaze amount", kind: "real" },
  { param: "vignetting_amount", jxa: "vignettingAmount", dictionary: "vignetting amount", kind: "real" },
  { param: "vignetting_method", jxa: "vignettingMethod", dictionary: "vignetting method", kind: "enum", values: ["elliptic on crop", "circular on crop", "circular"] as const },
  { param: "sharpening_amount", jxa: "sharpeningAmount", dictionary: "sharpening amount", kind: "real" },
  { param: "sharpening_radius", jxa: "sharpeningRadius", dictionary: "sharpening radius", kind: "real" },
  { param: "sharpening_threshold", jxa: "sharpeningThreshold", dictionary: "sharpening threshold", kind: "real" },
  { param: "sharpening_halo_suppression", jxa: "sharpeningHaloSuppression", dictionary: "sharpening halo suppression", kind: "real" },
  { param: "noise_reduction_luminance", jxa: "noiseReductionLuminance", dictionary: "noise reduction luminance", kind: "real" },
  { param: "noise_reduction_details", jxa: "noiseReductionDetails", dictionary: "noise reduction details", kind: "integer" },
  { param: "noise_reduction_color", jxa: "noiseReductionColor", dictionary: "noise reduction color", kind: "real" },
  { param: "noise_reduction_single_pixel", jxa: "noiseReductionSinglePixel", dictionary: "noise reduction single pixel", kind: "real" },
  { param: "film_grain_type", jxa: "filmGrainType", dictionary: "film grain type", kind: "enum", values: ["fine", "silver rich", "soft", "cubic", "tabular", "harsh"] as const },
  { param: "film_grain_impact", jxa: "filmGrainImpact", dictionary: "film grain impact", kind: "real" },
  { param: "film_grain_granularity", jxa: "filmGrainGranularity", dictionary: "film grain granularity", kind: "real" },
  { param: "moire_amount", jxa: "moireAmount", dictionary: "moire amount", kind: "real" },
  { param: "moire_pattern", jxa: "moirePattern", dictionary: "moire pattern", kind: "integer" },
] as const;

/** Structured properties this registry deliberately excludes: they are
 *  objects rather than scalars and need their own tool surface. */
export const COMPLEX_ADJUSTMENTS = [
  { dictionary: "color editor settings", jxa: "colorEditorSettings", type: "color editor options" },
  { dictionary: "rgb curve", jxa: "rgbCurve", type: "curve" },
  { dictionary: "luma curve", jxa: "lumaCurve", type: "curve" },
  { dictionary: "red curve", jxa: "redCurve", type: "curve" },
  { dictionary: "green curve", jxa: "greenCurve", type: "curve" },
  { dictionary: "blue curve", jxa: "blueCurve", type: "curve" },
  { dictionary: "dehaze color", jxa: "dehazeColor", type: "RGB color" },
] as const;
