// GENERATED by scripts/gen-recipes.py from the installed Capture One sdef.
// Do not hand-edit; re-run the generator instead.

export interface RecipeProperty {
  /** Tool-facing snake_case parameter name. */
  param: string;
  /** JXA property name on a recipe. */
  jxa: string;
  dictionary: string;
  kind: "real" | "integer" | "boolean" | "text" | "enum";
  values?: readonly string[];
}

export const RECIPE_PROPERTIES: readonly RecipeProperty[] = [
  { param: "name", jxa: "name", dictionary: "name", kind: "text" },
  { param: "enabled", jxa: "enabled", dictionary: "enabled", kind: "boolean" },
  { param: "output_format", jxa: "outputFormat", dictionary: "output format", kind: "enum", values: ["JPEG", "JPEG_QuickProof", "JPEG_XR", "JPEG_2000", "TIFF", "DNG", "PNG", "PSD", "PSB", "Affinity", "Original"] as const },
  { param: "bits", jxa: "bits", dictionary: "bits", kind: "integer" },
  { param: "jpeg_quality", jxa: "jpegQuality", dictionary: "JPEG quality", kind: "integer" },
  { param: "tiff_compression", jxa: "tiffCompression", dictionary: "TIFF compression", kind: "enum", values: ["Uncompressed", "LZW", "ZIP"] as const },
  { param: "tiff_thumbnail", jxa: "tiffThumbnail", dictionary: "TIFF thumbnail", kind: "boolean" },
  { param: "tiff_tile_dimension", jxa: "tiffTileDimension", dictionary: "TIFF tile dimension", kind: "integer" },
  { param: "color_profile", jxa: "colorProfile", dictionary: "color profile", kind: "text" },
  { param: "pixels_per_inch", jxa: "pixelsPerInch", dictionary: "pixels per inch", kind: "real" },
  { param: "scaling_method", jxa: "scalingMethod", dictionary: "scaling method", kind: "enum", values: ["Fixed", "Width_Scaling", "Height_Scaling", "BoundingDimensions", "Width_by_Height", "Long_Edge", "Short_Edge"] as const },
  { param: "scaling_unit", jxa: "scalingUnit", dictionary: "scaling unit", kind: "enum", values: ["pixels", "inches", "millimeters", "centimeters", "percent"] as const },
  { param: "primary_scaling_value", jxa: "primaryScalingValue", dictionary: "primary scaling value", kind: "real" },
  { param: "secondary_scaling_value", jxa: "secondaryScalingValue", dictionary: "secondary scaling value", kind: "real" },
  { param: "upscale", jxa: "upscale", dictionary: "upscale", kind: "boolean" },
  { param: "packed", jxa: "packed", dictionary: "packed", kind: "boolean" },
  { param: "include_adjustments", jxa: "includeAdjustments", dictionary: "include adjustments", kind: "boolean" },
  { param: "app", jxa: "app", dictionary: "app", kind: "text" },
  { param: "root_folder_type", jxa: "rootFolderType", dictionary: "root folder type", kind: "enum", values: ["output location", "image folder", "custom location"] as const },
  { param: "output_name_format", jxa: "outputNameFormat", dictionary: "output name format", kind: "text" },
  { param: "output_sub_name", jxa: "outputSubName", dictionary: "output sub name", kind: "text" },
  { param: "output_sub_folder", jxa: "outputSubFolder", dictionary: "output sub folder", kind: "text" },
  { param: "existing_files", jxa: "existingFiles", dictionary: "existing files", kind: "enum", values: ["add suffix", "overwrite", "skip"] as const },
  { param: "thumbnails", jxa: "thumbnails", dictionary: "thumbnails", kind: "boolean" },
  { param: "sharpening", jxa: "sharpening", dictionary: "sharpening", kind: "enum", values: ["no output sharpening", "for screen", "for print", "disable all"] as const },
  { param: "sharpening_amount", jxa: "sharpeningAmount", dictionary: "sharpening amount", kind: "real" },
  { param: "sharpening_radius", jxa: "sharpeningRadius", dictionary: "sharpening radius", kind: "real" },
  { param: "sharpening_threshold", jxa: "sharpeningThreshold", dictionary: "sharpening threshold", kind: "real" },
  { param: "sharpening_distance", jxa: "sharpeningDistance", dictionary: "sharpening distance", kind: "real" },
  { param: "sharpening_distance_type", jxa: "sharpeningDistanceType", dictionary: "sharpening distance type", kind: "enum", values: ["percent of diagonal", "inches", "centimeters"] as const },
  { param: "ignore_crop", jxa: "ignoreCrop", dictionary: "ignore crop", kind: "boolean" },
  { param: "export_crop_method", jxa: "exportCropMethod", dictionary: "export crop method", kind: "enum", values: ["respect", "ignore", "crop to path"] as const },
  { param: "include_ratings", jxa: "includeRatings", dictionary: "include ratings", kind: "boolean" },
  { param: "include_copyright", jxa: "includeCopyright", dictionary: "include copyright", kind: "boolean" },
  { param: "include_gps", jxa: "includeGPS", dictionary: "include GPS", kind: "boolean" },
  { param: "include_camera_metadata", jxa: "includeCameraMetadata", dictionary: "include Camera Metadata", kind: "boolean" },
  { param: "include_other_metadata", jxa: "includeOtherMetadata", dictionary: "include Other Metadata", kind: "boolean" },
  { param: "include_annotations", jxa: "includeAnnotations", dictionary: "include annotations", kind: "boolean" },
  { param: "include_overlay", jxa: "includeOverlay", dictionary: "include overlay", kind: "boolean" },
  { param: "include_guides", jxa: "includeGuides", dictionary: "include guides", kind: "boolean" },
] as const;

/** Writable recipe properties this registry excludes: lists and object
 *  references, which need a shape of their own rather than a scalar. */
export const RECIPE_UNSUPPORTED = [
  { dictionary: "root folder location", type: "file" },
  { dictionary: "include keywords", type: "text[]" },
  { dictionary: "watermark", type: "watermark" },
] as const;
