#!/usr/bin/env python3
"""Generate src/co/recipe-properties.ts from the installed app's sdef.

    python3 scripts/gen-recipes.py > src/co/recipe-properties.ts
"""
import os
import re
import xml.etree.ElementTree as ET

SDEF = os.environ.get("CO_SDEF", "reference/CaptureOne-16.8.5.sdef")
# 'number' appears alongside 'real' in this dictionary (pixels per inch,
# scaling values); dropping it silently lost three writable properties.
NUMERIC = {"real", "number"}
SIMPLE = NUMERIC | {"integer", "boolean", "text"}


def jxa_name(name):
    """AppleScript property name -> JXA identifier.

    JXA lowercases the FIRST word entirely -- so a leading acronym is folded
    ("JPEG quality" -> jpegQuality, "TIFF compression" -> tiffCompression) --
    while later words keep their own casing ("include GPS" -> includeGPS).
    Getting this wrong is silent: the accessor throws "Can't convert types.",
    which a defensive try/catch turns into a null nobody notices."""
    parts = name.split()
    return parts[0].lower() + "".join(p[0].upper() + p[1:] for p in parts[1:])


def main():
    root = ET.parse(SDEF).getroot()
    enums = {
        e.get("name"): [x.get("name") for x in e.findall("enumeration/enumerator")] or
                       [x.get("name") for x in e.findall("enumerator")]
        for s in root.findall("suite") for e in s.findall("enumeration")
    }

    rows, skipped = [], []
    for s in root.findall("suite"):
        for c in s.findall("class"):
            if c.get("name") != "recipe":
                continue
            for p in c.findall("property"):
                if p.get("access", "rw") != "rw":
                    continue
                types = p.findall("type")
                t = types[0].get("type") if types else p.get("type")
                is_list = (types[0].get("list") == "yes") if types else (p.get("list") == "yes")
                name = p.get("name")
                if is_list:
                    skipped.append((name, t + "[]"))      # lists need their own shape
                    continue
                if t in SIMPLE:
                    kind = "real" if t in NUMERIC else t
                    rows.append((name, jxa_name(name), kind, None))
                elif t in enums:
                    rows.append((name, jxa_name(name), "enum", enums[t]))
                else:
                    skipped.append((name, t))             # watermark object, file refs

    print("// GENERATED by scripts/gen-recipes.py from the installed Capture One sdef.")
    print("// Do not hand-edit; re-run the generator instead.\n")
    print("export interface RecipeProperty {")
    print("  /** Tool-facing snake_case parameter name. */")
    print("  param: string;")
    print("  /** JXA property name on a recipe. */")
    print("  jxa: string;")
    print("  dictionary: string;")
    print('  kind: "real" | "integer" | "boolean" | "text" | "enum";')
    print("  values?: readonly string[];")
    print("}\n")
    print("export const RECIPE_PROPERTIES: readonly RecipeProperty[] = [")
    for name, j, kind, vals in rows:
        param = re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")
        entry = f'  {{ param: "{param}", jxa: "{j}", dictionary: "{name}", kind: "{kind}"'
        if vals:
            entry += ", values: [" + ", ".join(f'"{v}"' for v in vals) + "] as const"
        print(entry + " },")
    print("] as const;\n")
    print("/** Writable recipe properties this registry excludes: lists and object")
    print(" *  references, which need a shape of their own rather than a scalar. */")
    print("export const RECIPE_UNSUPPORTED = [")
    for name, t in skipped:
        print(f'  {{ dictionary: "{name}", type: "{t}" }},')
    print("] as const;")


if __name__ == "__main__":
    main()
