#!/usr/bin/env python3
"""Generate src/co/adjustment-properties.ts from the installed app's sdef.

The adjustment surface is ~90 properties. Hand-maintaining that list would drift
from the app, so the registry, the tool schema and the round-trip test harness
are all driven from this one generated file.

    python3 scripts/gen-adjustments.py > src/co/adjustment-properties.ts
"""
import os
import re
import xml.etree.ElementTree as ET

SDEF = os.environ.get("CO_SDEF", "reference/CaptureOne-16.8.5.sdef")
SIMPLE = {"real", "integer", "boolean", "text"}


def jxa_name(name):
    """AppleScript property name -> JXA identifier.

    JXA lowercases the FIRST word entirely -- so a leading acronym is folded
    ("JPEG quality" -> jpegQuality, "TIFF compression" -> tiffCompression) --
    while later words keep their own casing ("include GPS" -> includeGPS).
    Getting this wrong is silent: the accessor throws "Can't convert types.",
    which a defensive try/catch turns into a null nobody notices."""
    parts = name.split()
    return parts[0].lower() + "".join(p[0].upper() + p[1:] for p in parts[1:])


def snake(name):
    return re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def main():
    root = ET.parse(SDEF).getroot()
    enums = {}
    for s in root.findall("suite"):
        for e in s.findall("enumeration"):
            enums[e.get("name")] = [x.get("name") for x in e.findall("enumerator")]

    rows = []
    for s in root.findall("suite"):
        for c in s.findall("class"):
            if c.get("name") != "adjustment settings":
                continue
            for p in c.findall("property"):
                types = p.findall("type")
                t = types[0].get("type") if types else p.get("type")
                rows.append((p.get("name"), t))

    print("// GENERATED by scripts/gen-adjustments.py from the installed Capture One sdef.")
    print("// Do not hand-edit; re-run the generator instead.\n")
    print("export interface AdjustmentProperty {")
    print("  /** Tool-facing snake_case parameter name. */")
    print("  param: string;")
    print("  /** JXA property name on `variant.adjustments`. */")
    print("  jxa: string;")
    print("  /** Name as it appears in the scripting dictionary. */")
    print("  dictionary: string;")
    print('  kind: "real" | "integer" | "boolean" | "enum" | "text";')
    print("  /** Allowed values, for enum-typed properties. */")
    print("  values?: readonly string[];")
    print("}\n")

    print("export const ADJUSTMENT_PROPERTIES: readonly AdjustmentProperty[] = [")
    for name, t in rows:
        if t in SIMPLE:
            kind = t
            vals = None
        elif t in enums:
            kind = "enum"
            vals = enums[t]
        else:
            continue  # curves, colour editor, RGB colour -- handled separately
        entry = (
            f'  {{ param: "{snake(name)}", jxa: "{jxa_name(name)}", '
            f'dictionary: "{name}", kind: "{kind}"'
        )
        if vals:
            entry += ", values: [" + ", ".join(f'"{v}"' for v in vals) + "] as const"
        print(entry + " },")
    print("] as const;\n")

    complex_rows = [(n, t) for n, t in rows if t not in SIMPLE and t not in enums]
    print("/** Structured properties this registry deliberately excludes: they are")
    print(" *  objects rather than scalars and need their own tool surface. */")
    print("export const COMPLEX_ADJUSTMENTS = [")
    for n, t in complex_rows:
        print(f'  {{ dictionary: "{n}", jxa: "{jxa_name(n)}", type: "{t}" }},')
    print("] as const;")


if __name__ == "__main__":
    main()
